theme               : jekyll-theme-minimal
title               : [Fairness Measures]
description         : [Datasets and Software for Detecting Algorithmic Discrimination]
show_downloads      : ["false"]
google_analytics    : [UA-101054904-1]
baseurl             : ""